### ISSUE TITLE
I'm having trouble generating ticket printing

### ISSUE THREAD

**Issue by alexventrizi** [vivalite/VRArcadeSoftware#1]
Hello,
I'm having trouble generating ticket printing. Whether by waiver or single print, the system returns the following message:

Error! Object reference not set to an instance of an object.

As I did not find references in the documentation, I have this problem to solve ..

Do you have any idea what it might be?

Best regards,

![image](https://user-images.githubusercontent.com/7069370/83079569-83f73480-a052-11ea-83bc-dd9b4566e2e1.png)

**Comment by vivalite** [comment]
You need to install the thermal printer drive and POS for .Net v1.12 component to use the printing feature, 

I have now includeded the installer here: https://github.com/vivalite/VRArcadeSoftware/tree/master/DOCs/!Thermal%20Printer
